"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user16PFTestController_1 = require("../controllers/user16PFTestController");
var router = (0, express_1.Router)();
router.post('/', user16PFTestController_1.createUser16PFTest);
router.get('/', user16PFTestController_1.getUser16PFTests);
router.get('/:id', user16PFTestController_1.getUser16PFTestById);
router.put('/:id', user16PFTestController_1.updateUser16PFTest);
router.delete('/:id', user16PFTestController_1.deleteUser16PFTest);
exports.default = router;
